add example for tensorflow
t9k/asset-hub-example pull request #3
Opened 2022-12-02 03:22 UTC by shenkejie15

增加了 tensorflow mnist 的例子。

有一个已知的问题，tensorflow 2.8.0 使用 cpu 训练时有较高概率在训练完成后报错 core dumped，因此这里使用了 GPU。使用的队列是 a100，使用的资源是 CPU: 16, Memory: 8Gi, tensorstack.dev/nvidia-gpu: 2。这么设置是为了在 nc201 顺利运行，但不利于迁移。

2022-12-02 03:23 UTC, shenkejie15 commented
使用这里的代码进行训练、继续训练、评估的例子参考 https://proxy.nc201.kube.tensorstack.net/t9k/asset-hub/web/#/models/3623abde-b06d-4c44-9e3c-024f3a675268/280551d6-bca5-447a-b753-6e5e5ca56655/?tab=training（用户为 demo）

2022-12-02 04:19 UTC, ppkube commented
> 有一个已知的问题，tensorflow 2.8.0 使用 CPU 训练时有较高概率在训练完成后报错 core dumped，因此这里使用了 GPU

不要使用 GPU，可以换换 tf 的版本试试

2022-12-02 04:21 UTC, ppkube commented on mnist-tensorflow/workflow-train.yaml
> +    - name: request_cpu
这些 resource 相关的 params 都去掉，直接放到 yaml 里

2022-12-02 04:29 UTC, ppkube requested changes

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-train.yaml
> +      value: registry.tensorstack.cn/t9kmirror/tensorflow:2.8.0
use a newer version of tensorflow?

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-continue.yaml
> +    - name: request_cpu
remove resource related params

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-continue.yaml
> +          backoffLimit: 0           # 所有Pod最多共重启0次
remove comments

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-continue.yaml
> +        scheduler:
remove scheduler config

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-continue.yaml
> +    - name: worker_num
remove worker_num

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-evaluate.yaml
> +    - name: request_cpu
ditto

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-evaluate.yaml
> +          backoffLimit: 5           # 所有Pod最多共重启20次
ditto

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-evaluate.yaml
> +                  runAsUser: 1000
explain why 1000 is used. That tensorflow image sets user = 1000?

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-evaluate.yaml
> +      value: registry.tensorstack.cn/t9kmirror/tensorflow:2.8.0
ditto

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/workflow-train.yaml
> +                  runAsUser: 1000
ditto

2022-12-02 04:29 UTC, ppkube commented on mnist-tensorflow/evaluate.py
> +    test_images = test_images.reshape((10000, 28, 28, 1))
explain why these numbers are used

2022-12-02 06:59 UTC, shenkejie15 commented on mnist-tensorflow/workflow-evaluate.yaml
> +                  runAsUser: 1000
和 tensorflow 无关。

Asset Hub launcher workflow 使用 t9k/build-sdk 镜像执行下载 Git 代码、下载 Asset、上传 Asset 的任务。t9k/build-sdk 使用的 uid 是 1000。

2022-12-02 07:19 UTC, shenkejie15 commented on mnist-tensorflow/workflow-train.yaml
> +      value: registry.tensorstack.cn/t9kmirror/tensorflow:2.8.0
改成了最新的 2.11.0，但是现在集群中 trainingjob 可能无法使用，所以没有实际测试过。

2022-12-05 04:18 UTC, shenkejie15 commented on mnist-tensorflow/workflow-continue.yaml
> +    - name: worker_num
fixed

2022-12-05 04:19 UTC, merged